# Operadores aritimeticos =
# + SOMA
# - SUBTRACAO
# * MULTIPLICACAO
# / DIVISAO
# % RESTO DA DIVISAO
# ** AO QUADRADO


#OPERADORES DE COMPARACAO
# == IGUAL
# != DIFERENTE
# > MAIOR
# < MENOE
# >= MAIOR OU IGUAL
# <= MENOR OU IGUAL



#OPERADORES LOGICOS
#AND  OS DOIS TEM QUE SER VERDADEIROS
#OR   APENAS UM TEM QUE SER VERDADEIRO
#NOT  AO CONTRARIO